### ISSUE TITLE
Usability with Canopus devices

### ISSUE THREAD

**Issue by jdemeule** [MyCometG3/recdv2#1]
Hello,

I discover this repository during my attempt to fix some import issue with Canopus ADVC 300 device on iMovie and QuickTime Player.
iMovie allows me to record the stream however I do have a reliable preview monitor and QuickTime Player does not record anything.

I manage to compile your code and I face an issue similar to QuickTime Player. A quick debug session give me that:
 * the device is detected correctly (muxed one)
 * the format reported by AVCaptureDevice seems invalid (size of [0,0]).

Do you know if it is possible to do something or we face some limitation of AVFoundation about DV capture?

Thanks,
Jeremy

**Comment by MyCometG3** [comment]
Possibly timecode issue - see following:

> https://discussions.apple.com/thread/8537996.
> https://mygrassvalleyportal.secure.force.com/gvknowledge/articles/KB_Article/ADVC-300-is-having-problems-with-the-time-cut-being-lost/?l=en_US&c=Products%3Acam_hd_LDK_Series%2CProducts%3ADD20&fs=RelatedArticle
